export const GLOBAL_EN = {
  add: 'Add',
  search: 'Search',
  requiredField: 'Required field!',
  cancel: 'Cancel',
  list: 'List',
  EntityDoesNotExistException: 'Unable to access the requested resource',
  NotAuthorizedException: 'Wrong credentials',
  FailedToFetchException: 'Server connection error',
  ForbiddenException: 'You do not have necessary permissions',
  BadRequestException: 'Error: Contact Administrator',
  InternalServerErrorException: 'Error: Contact Administrator',
  InvalidArgumentException: 'Error: Contact Administrator',
  InternalException: 'Error: Contact Administrator',
  GetWorkItemFieldsFailedException:
    'The requested fields of the Work Item could not be found correctly, try again later.',
  CreateDocumentFailedException: 'Error adding an entry to the document, please try again',
  FieldUpdateFailedException: 'Error when trying to update the fields of the work item, try again',
  GetWorkItemsException: 'Error trying to get the work items.',
  remove: 'Remove',
  tableLabelDisplay: '{{0}}-{{1}} of {{2}}',
  name: 'Name',
  id: 'Id',
  removeTextInfo: 'Are you sure you want to remove {{0}}?',
  confirm: 'Confirm',
  removeTitle: 'Remove {{0}}',
  noResultsFound: 'No results',
  results: 'Results',
  showing: 'Showing',
  status: 'Status',
  createTitle: 'Create {{0}}',
  date: 'Date',
  yes: 'Yes',
  no: 'No',
  accept: 'Accept',
  basicInfo: 'Basic information',
  type: 'Type',
  downloadPdf: 'Download pdf',
  downloadCSV: 'Download csv',
  downloading: 'Downloading...',
  description: 'Description',
  user: 'User',
  to: 'To',
  from: 'From',
  types: 'Types',
  new: 'New',
  statuses: 'Statuses',
  none: 'None',
  save: 'Save',
  newMale: 'New',
  number: 'Number',
  download: 'Download',
  summary: 'Summary',
  total: 'Total',
  users: 'Users',
  actions: 'Actions',
  time: 'Time',
  activity: 'Activity',
  notes: 'Notes',
  timelogEntries: 'Time Log Entries',
  minutes: 'Minutes',
  hours: 'Hours',
  newTimelogEntry: 'New Time Log Entry',
  notZeroTime: 'Entry needs some time',
  filters: 'Filters',
  all: 'All',
  teams: 'Teams',
  workItem: 'Work Item',
  addTimeLog: 'Add Time Log',
  addActivity: 'Add Activity',
  createdOn: 'Created On',
  createdBy: 'Created By',
  newActivity: 'New Activity',
  activities: 'Activities',
  activityManagement: 'Activity Management',
  about: 'About',
  entriesCount: 'Entries Count',
  avaragePerDay: 'Avarage (per day)',
  dashboard: 'Dashboard',
  logEntries: 'Log Entries',
  contact: 'Contact',
  poweredBy: 'Powered By',
  version: 'Version',
  aboutTimeLogForAzureDevOps: 'About Time Log For Azure DevOps',
  loading: 'Loading',
  chooseOrganization: 'Choose the organization you want to link to Azure DevOps:',
  chooseProjects: 'Choose the project you want to link to Azure DevOps:',
  organization: 'Organization',
  project: 'Project',
  continue: 'Continue',
  login: 'Log in',
  noResultsMessage: `We couldn't find any matches.`,
  chooseWorkitem: 'Select WorkItem...',
  chooseActivity: 'Select Activity...',
  successTimeLogTitle: 'Time logged successfully!',
  successTimeLogInfo: 'You just completed the new time log.',
  unableAccessToDevOps: 'Please make sure you are signing in with an account with access to ',
  noExtensionMessage:
    'You need to have TimeLog for Azure DevOps installed in your organization to use this extension (Make sure you are an Administrator or contact your Azure DevOps administrator)',
  tryAgain: 'Try Again',
  unableOrganization:
    'Please make sure you have an account with access to an Azure DevOps organization in order to continue.',
  unableProjects: 'Please make sure you have an account with access to a Azure DevOps project in order to continue.',
  unableWorkItems: 'Within the Azure DevOps organization there should be work Items available.',
  postMessage: 'Post message',
  stats: 'Stats',
  timeLoggedGrouped: 'Time Logged Grouped',
  areaPath: 'Area Path',
  tag: 'Tag',
  timeLogged: 'Time Logged',
  timeLoggedBy: 'Time Logged by',
  chartType: 'Chart Type',
  groupBy: 'Group By',
  weeklyTimeLogged: 'Weekly Time Logged',
  week: 'Week',
  people: 'People',
};
