export const GLOBAL_EN = {
  add: 'Add',
  search: 'Search',
  requiredField: 'Required field!',
  cancel: 'Cancel',
  list: 'List',
  EntityDoesNotExistException: 'Unable to access the requested resource',
  NotAuthorizedException: 'wrong credentials',
  FailedToFetchException: 'Server connection error',
  ForbiddenException: 'You do not have necessary permissions',
  BadRequestException: 'Error: Contact Administrator',
  InternalServerErrorException: 'Error: Contact Administrator',
  InvalidArgumentException: 'Error: Contact Administrator',
  InternalException: 'Error: Contact Administrator',
  remove: 'Remove',
  tableLabelDisplay: '{{0}}-{{1}} of {{2}}',
  name: 'Name',
  id: 'Id',
  removeTextInfo: 'Are you sure you want to remove {{0}}?',
  confirm: 'Confirm',
  removeTitle: 'Remove {{0}}',
  noResultsFound: 'No results',
  results: 'Results',
  showing: 'Showing',
  status: 'Status',
  createTitle: 'Create {{0}}',
  date: 'Date',
  yes: 'Yes',
  no: 'No',
  accept: 'Accept',
  basicInfo: 'Basic information',
  type: 'Type',
  downloadPdf: 'Download pdf',
  downloadCSV: 'Download csv',
  downloading: 'Downloading...',
  description: 'Description',
  user: 'User',
  to: 'To',
  from: 'From',
  types: 'Types',
  new: 'New',
  statuses: 'Statuses',
  none: 'None',
  save: 'Save',
  newMale: 'New',
  number: 'Number',
  download: 'Download',
  summary: 'Summary',
  total: 'Total',
  users: 'Users',
  actions: 'Actions',
  time: 'Time',
  activity: 'Activity',
  notes: 'Notes',
  timelogEntries: 'Time log Entries',
  minutes: 'Minutes',
  hours: 'Hours',
  newTimelogEntry: 'New Time log Entry',
  notZeroTime: 'Entry needs some time',
  filters: 'Filters',
  all: 'All',
  teams: 'Teams',
  workItem: 'Work Item',
  addTimeLog: 'Add Time Log',
  addActivity: 'Add Activity',
  createdOn: 'Created On',
  createdBy: 'Created By',
  newActivity: 'New Activity',
  activities: 'Activities',
  activityManagement: 'Activity Management',
  about: 'About',
  entriesCount: 'Entries Count',
  avaragePerDay: 'Avarage (per day)',
  dashboard: 'Dashboard',
  logEntries: 'Log Entries',
  contact: 'Contact',
  poweredBy: 'Power By',
  version: 'Version',
  aboutTimeLogForAzureDevOps: 'About Time Log For Azure DevOps',
};
