export const GLOBAL_ES = {
  add: 'Añadir',
  search: 'Buscar',
  requiredField: '¡Campo requerido!',
  cancel: 'Cancelar',
  list: 'Lista',
  EntityDoesNotExistException: 'No se puede acceder al recurso solicitado',
  NotAuthorizedException: 'Credenciales incorrectas',
  FailedToFetchException: 'Error de conexión con el servidor',
  ForbiddenException: 'No tienes permisos necesarios',
  BadRequestException: 'Error: Ponte en contacto con el Administrador',
  InternalServerErrorException: 'Error: Ponte en contacto con el Administrador',
  InvalidArgumentException: 'Error: Ponte en contacto con el Administrador',
  InternalException: 'Error: Ponte en contacto con el Administrador',
  GetWorkItemFieldsFailedException:
    'No se han podido encontrar correctamente los campos solicitados del Work Item, intentalo de nuevo mas tarde.',
  CreateDocumentFailedException: 'Error al añadir una entrada en el documento, intentelo de nuevo.',
  FieldUpdateFailedException: 'Error al intentar actualizar los campos del work item, intentelo de nuevo.',
  GetWorkItemsException: 'Error al intentar obtener los work items.',
  remove: 'Eliminar',
  tableLabelDisplay: '{{0}}-{{1}} de {{2}}',
  name: 'Nombre',
  id: 'Id',
  removeTextInfo: '¿Está seguro de que desea eliminar {{0}}?',
  confirm: 'Confirmar',
  removeTitle: 'Eliminar {{0}}',
  noResultsFound: 'No hay resultados',
  results: 'Resultados',
  showing: 'Mostrando',
  status: 'Estado',
  createTitle: 'Crear {{0}}',
  date: 'Fecha',
  yes: 'Si',
  no: 'No',
  accept: 'Aceptar',
  basicInfo: 'Información Básica',
  type: 'Tipo',
  downloadPdf: 'Descargar PDF',
  downloadCSV: 'Descargar CSV',
  downloading: 'Descargando...',
  description: 'Descripción',
  user: 'Usuario',
  to: 'Hasta',
  from: 'Desde',
  types: 'Tipos',
  new: 'Nueva',
  statuses: 'Estados',
  none: 'Ninguno',
  save: 'Guardar',
  newMale: 'Nuevo',
  number: 'Número',
  download: 'Descargar',
  summary: 'Resumen',
  total: 'Total',
  users: 'Usuarios',
  actions: 'Acciones',
  time: 'Tiempo',
  activity: 'Actividad',
  notes: 'Notas',
  timelogEntries: 'Registros de tiempo',
  minutes: 'Minutos',
  hours: 'Horas',
  newTimelogEntry: 'Nuevo Registro de tiempo',
  notZeroTime: 'La entrada necesita tiempo',
  filters: 'Filtros',
  all: 'Todos',
  teams: 'Teams',
  workItem: 'Work Item',
  addTimeLog: 'Añadir Registro de tiempo',
  addActivity: 'Añadir Actividad',
  createdOn: 'Creado En',
  createdBy: 'Creado Por',
  newActivity: 'Nueva Actividad',
  activities: 'Actividades',
  activityManagement: 'Gestión de Actividades',
  about: 'Acerca de',
  entriesCount: 'Número de registros',
  avaragePerDay: 'Promedio (por día)',
  dashboard: 'Dashboard',
  logEntries: 'Registros de tiempo',
  contact: 'Contacto',
  poweredBy: 'Powered By',
  version: 'Versión',
  aboutTimeLogForAzureDevOps: 'Acerca de Time Log para Azure DevOps',
  loading: 'Cargando',
  chooseOrganization: 'Elija la organización que desea vincular a Azure DevOps:',
  chooseProjects: 'Elija el proyecto que desea vincular a Azure DevOps:',
  organization: 'Organización',
  project: 'Proyecto',
  continue: 'Continuar',
  login: 'Iniciar sesión',
  noResultsMessage: `We couldn't find any matches.`,
  chooseWorkitem: 'Selecciona un WorkItem...',
  chooseActivity: 'Selecciona una Actividad...',
  successTimeLogTitle: '¡Tiempo registrado con éxito!',
  successTimeLogInfo: 'Acabas de completar el nuevo registro de tiempo.',
  unableAccessToDevOps: 'Asegúrese de iniciar sesión con una cuenta con acceso a ',
  noExtensionMessage:
    'Debe tener TimeLog para Azure DevOps instalado en su organización para usar esta extensión (Asegurese de ser Administrador o pongase en contacto con el administrador de su Azure DevOps)',
  tryAgain: 'Intentar de nuevo',
  unableOrganization:
    'Por favor, asegúrese de tener una cuenta con acceso a una organización de Azure DevOps para poder continuar.',
  unableProjects:
    'Por favor, asegúrese de tener una cuenta con acceso a un proyecto de Azure DevOps para poder continuar.',
  unableWorkItems: 'Dentro de la organización de Azure DevOps debe haber elementos de trabajo disponibles.',
  postMessage: 'Publicar mensaje',
  stats: 'Estadísticas',
  timeLoggedGrouped: 'Tiempo registrado agrupado',
  areaPath: 'Ruta de área',
  tag: 'Etiqueta',
  timeLogged: 'Tiempo registrado',
  timeLoggedBy: 'Tiempo registrado por',
  chartType: 'Tipo de Gráfico',
  groupBy: 'Agrupado Por',
  weeklyTimeLogged: 'Tiempo semanal registrado',
  week: 'Semana',
  people: 'Miembros',
};
