export const GLOBAL_ES = {
  add: 'Añadir',
  search: 'Buscar',
  requiredField: '¡Campo requerido!',
  cancel: 'Cancelar',
  list: 'Lista',
  EntityDoesNotExistException: 'No se puede acceder al recurso solicitado',
  NotAuthorizedException: 'Credenciales incorrectas',
  FailedToFetchException: 'Error de conexión con el servidor',
  ForbiddenException: 'No tienes permisos necesarios',
  BadRequestException: 'Error: Ponte en contacto con el Administrador',
  InternalServerErrorException: 'Error: Ponte en contacto con el Administrador',
  InvalidArgumentException: 'Error: Ponte en contacto con el Administrador',
  InternalException: 'Error: Ponte en contacto con el Administrador',
  remove: 'Eliminar',
  tableLabelDisplay: '{{0}}-{{1}} de {{2}}',
  name: 'Nombre',
  id: 'Id',
  removeTextInfo: '¿Está seguro de que desea eliminar {{0}}?',
  confirm: 'Confirmar',
  removeTitle: 'Eliminar {{0}}',
  noResultsFound: 'No hay resultados',
  results: 'Resultados',
  showing: 'Mostrando',
  status: 'Estado',
  createTitle: 'Crear {{0}}',
  date: 'Fecha',
  yes: 'Si',
  no: 'No',
  accept: 'Aceptar',
  basicInfo: 'Información Básica',
  type: 'Tipo',
  downloadPdf: 'Descargar PDF',
  downloadCSV: 'Descargar CSV',
  downloading: 'Descargando...',
  description: 'Descripción',
  user: 'Usuario',
  to: 'Hasta',
  from: 'Desde',
  types: 'Tipos',
  new: 'Nueva',
  statuses: 'Estados',
  none: 'Ninguno',
  save: 'Guardar',
  newMale: 'Nuevo',
  number: 'Número',
  download: 'Descargar',
  summary: 'Resumen',
  total: 'Total',
  users: 'Usuarios',
  actions: 'Acciones',
  time: 'Tiempo',
  activity: 'Actividad',
  notes: 'Notas',
  timelogEntries: 'Registros de tiempo',
  minutes: 'Minutos',
  hours: 'Horas',
  newTimelogEntry: 'Nuevo Registro de tiempo',
  notZeroTime: 'La entrada necesita tiempo',
  filters: 'Filtros',
  all: 'Todos',
  teams: 'Teams',
  workItem: 'Work Item',
  addTimeLog: 'Añadir Registro de tiempo',
  addActivity: 'Añadir Actividad',
  createdOn: 'Creado En',
  createdBy: 'Creado Por',
  newActivity: 'Nueva Actividad',
  activities: 'Actividades',
  activityManagement: 'Gestión de Actividades',
  about: 'Acerca de',
  entriesCount: 'Número de registros',
  avaragePerDay: 'Promedio (por día)',
  dashboard: 'Dashboard',
  logEntries: 'Registros de tiempo',
  contact: 'Contacto',
  poweredBy: 'Power By',
  version: 'Versión',
  aboutTimeLogForAzureDevOps: 'Acerca de Time Log para Azure DevOps',
  loading: 'Cargando',
  chooseOrganization: 'Elija la organización que desea vincular a Azure DevOps:',
  chooseProjects: 'Elija el proyecto que desea vincular a Azure DevOps:',
  organization: 'Organización',
  project: 'Proyecto',
  continue: 'Continuar',
};
